[package]
name = "euclid"
version = "0.8.0"
authors = ["The Servo Project Developers"]
description = "Geometry primitives"
documentation = "http://doc.servo.org/euclid/"
repository = "https://github.com/servo/euclid"
license = "MIT / Apache-2.0"

[features]
default = []
plugins = []
unstable = []

[dependencies]
heapsize = ">=0.2, <0.4"
rustc-serialize = "0.3.2"
num-traits = {version = "0.1.32", default-features = false}
log = "0.3.1"
serde = ">=0.6, <0.8"

[dev-dependencies]
rand = "0.3.7"
